// <auto-generated />
using System;
using Betonchel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Betonchel.Data.Migrations
{
    [DbContext(typeof(BetonchelContext))]
    partial class BetonchelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Betonchel.Domain.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationCreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ConcreteGradeId")
                        .HasColumnType("integer");

                    b.Property<int>("ConcretePumpId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactData")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("json");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<double>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<float>("Volume")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ConcreteGradeId");

                    b.HasIndex("ConcretePumpId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");

                    b.HasCheckConstraint("CK_DeliveryDate", "\"DeliveryDate\" > now()");

                    b.HasCheckConstraint("CK_TotalPrice", "\"TotalPrice\" >= 0");

                    b.HasCheckConstraint("CK_Volume", "\"Volume\" >= 0");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.ConcreteGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<int>("FrostResistanceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<double>("PricePerCubicMeter")
                        .HasColumnType("double precision");

                    b.Property<int>("WaterproofTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FrostResistanceTypeId");

                    b.HasIndex("WaterproofTypeId");

                    b.ToTable("ConcreteGrades");

                    b.HasCheckConstraint("CK_PricePerCubicMeter", "\"PricePerCubicMeter\" >= 0");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.ConcretePump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("MaximumCapacity")
                        .HasColumnType("real");

                    b.Property<float?>("PipeLength")
                        .HasColumnType("real");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConcretePumps");

                    b.HasCheckConstraint("CK_MaximumCapacity", "\"MaximumCapacity\" >= 0");

                    b.HasCheckConstraint("CK_PipeLength", "\"PipeLength\" >= 0");

                    b.HasCheckConstraint("CK_PricePerHour", "\"PricePerHour\" >= 0");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.FrostResistanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("FrostResistanceTypes");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactData")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.WaterproofType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("WaterproofTypes");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.Application", b =>
                {
                    b.HasOne("Betonchel.Domain.Models.ConcreteGrade", "ConcreteGrade")
                        .WithMany("Applications")
                        .HasForeignKey("ConcreteGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Betonchel.Domain.Models.ConcretePump", "ConcretePump")
                        .WithMany("Applications")
                        .HasForeignKey("ConcretePumpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Betonchel.Domain.Models.User", "User")
                        .WithMany("Application")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConcreteGrade");

                    b.Navigation("ConcretePump");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.ConcreteGrade", b =>
                {
                    b.HasOne("Betonchel.Domain.Models.FrostResistanceType", "FrostResistanceType")
                        .WithMany("ConcreteGrades")
                        .HasForeignKey("FrostResistanceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Betonchel.Domain.Models.WaterproofType", "WaterproofType")
                        .WithMany("ConcreteGrades")
                        .HasForeignKey("WaterproofTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FrostResistanceType");

                    b.Navigation("WaterproofType");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.ConcreteGrade", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.ConcretePump", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.FrostResistanceType", b =>
                {
                    b.Navigation("ConcreteGrades");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.User", b =>
                {
                    b.Navigation("Application");
                });

            modelBuilder.Entity("Betonchel.Domain.Models.WaterproofType", b =>
                {
                    b.Navigation("ConcreteGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
